add fixes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,7 @@
 name: OpenELIS-Global-2 CI Build
 on:
   push:
-    branches: [develop]
+    branches: [feat/multitenancy, demo/tenant]
   pull_request:
   workflow_dispatch:
 
@@ -52,12 +52,12 @@ jobs:
       - name: Fix permissions
         if: github.event_name == 'push'
         run: |
-              sudo chown -R $(whoami):$(whoami) target/html
-              sudo chmod -R 755 target/html  # Read-write for owner, read for others
+          sudo chown -R $(whoami):$(whoami) target/html
+          sudo chmod -R 755 target/html  # Read-write for owner, read for others
 
       - name: Check coverage report exists
         if: github.event_name == 'push'
-        run: ls -lah target/html || echo "Coverage report not found!"     
+        run: ls -lah target/html || echo "Coverage report not found!"
 
       - name: Publish coverage report to GitHub Pages
         if: github.event_name == 'push'
